apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - port: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - port: 15672
    # name: management
    # targetPort: 15672  