apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        exact: /identity/connect/auth
    - uri:
        prefix: /identity/connect
    route:
    - destination:
        host: keycloak-http.eshop.svc.cluster.local
        port:
          number: 8443
  - match:
    - uri:
        regex: /identity/connect
    route:
    - destination:
        host: keycloak-http.eshop.svc.cluster.local
        port:
          number: 8443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: keycloak
  namespace: eshop
spec:
  host: keycloak-http.eshop.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
