## Istio + Keycloak + Oauth2 proxy 인증 적용

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-vs
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        exact: /prometheus
    - uri:
        prefix: /prometheus/
    rewrite:
      uri: "/"
    route:
    - destination:
        host: eshop-prometheus-server.eshop.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: prometheus
  namespace: eshop
spec:
  host: eshop-prometheus-server.eshop.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE     
---




